CREATE TABLE IF NOT EXISTS `user`
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    serial VARCHAR (255) NOT NULL,
    username VARCHAR (255) NOT NULL,
    full_name VARCHAR (255) NOT NULL,
    role VARCHAR (40) NOT NULL,
    email VARCHAR (255) NOT NUlL,
    password VARCHAR (255) NOT NULL,
    gender VARCHAR (255) NOT NULL,
    photo_url VARCHAR (255) NOT NULL,
    phone_number VARCHAR (255) NOT NULL,
    address TEXT NOT NULL,
    status VARCHAR (40) NOT NULL,
    access_status VARCHAR (40) NOT NULL,
    registration_otp VARCHAR (16) NOT NULL,
    forgot_password_token VARCHAR (16) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UC_SERIAL UNIQUE (serial),
    CONSTRAINT UC_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS `user_token`
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_serial VARCHAR (255) NOT NULL,
    refresh_token VARCHAR (255) NOT NULL,
    CONSTRAINT UC_user_serial UNIQUE (user_serial)
);

CREATE TABLE IF NOT EXIST `villager`
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    serial VARCHAR (255) NOT NULL,
    id_ktp VARCHAR (255) NOT NULL,
    full_name VARCHAR (255) NOT NULL,
    id_kk VARCHAR (255) NOT NULL,
    address VARCHAR (255) NOT NULL,
    RT VARCHAR (10) NOT NULL,
    RW VARCHAR (10) NOT NULL,
    status VARCHAR (255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UC_id_ktp UNIQUE (id_ktp)
    CONSTRAINT UC_serial UNIQUE (serial)
    );

CREATE TABLE IF NOT EXIST `family`
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    kk_id VARCHAR (255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UC_kk_id UNIQUE (kk_id)
);

CREATE TABLE IF NOT EXIST `villager_family`
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    kk_id VARCHAR (255) NOT NULL,
    villager_id VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UC_kk_id_villager_id UNIQUE (kk_id, villager_id)
);

CREATE TABLE IF NOT EXIST `village`
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    serial VARCHAR (255) NOT NULL,
    name VARCHAR (255) NOT NULL,
    geo_location VARCHAR (255) NOT NULL,
    CONSTRAINT UC_serial UNIQUE (serial)
);